server:
  port: 8080
  context-path: /
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://database:3306/license?useUnicode=true&charaterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: number
    password: validator